[package]
name = "esr-wasm"
version = "0.1.0"
authors = ["Matthias Thoemmes <thoemmes@gmail.com>"]

[dependencies]
serde_json = "1.0"
esr = { path = "../esr", version = "0.1.0" }
esr-codegen = { path = "../esr-codegen", version = "0.1.0" }
