[package]
name = "esr-wasm"
version = "0.1.0"
authors = ["Tzvi Melamed <tzvi@melamed.biz>"]
license = "MIT"
edition = "2018"

[dependencies]
serde_json = "1.0"
esr = { path = "../esr", version = "0.1.0" }
esr-codegen = { path = "../esr-codegen", version = "0.1.0" }
